modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="lollikzombieshift"
version="2.0"
displayName="Lollik Zombie Shift"
description="Transform into ghost zombie with R key"
authors="Lollik"

[[dependencies.lollikzombieshift]]
modId="forge"
versionRange="[36.2.0,)"
mandatory=true

[[dependencies.lollikzombieshift]]
modId="minecraft"
versionRange="[1.16.5,1.17)"
mandatory=true
