name: Build Mod
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install and use Gradle 6.8.3
        run: |
          wget https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
          unzip gradle-6.8.3-bin.zip
          ./gradle-6.8.3/bin/gradle build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LollikZombieShift
          path: build/libs/*.jar
