name: Build Mod
on: [push]

jobs:
  build:
    # Используем ubuntu-latest для CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- НОВЫЙ ДИАГНОСТИЧЕСКИЙ ШАГ ---
      - name: Check Gradle Wrapper Files (Diagnostic)
        run: |
          echo "Listing contents of gradle/wrapper/ directory:"
          # Показываем содержимое папки. Если файлы отсутствуют, вы увидите ошибку или пустой список.
          ls -la gradle/wrapper/ || echo "CRITICAL ERROR: gradle/wrapper directory not found or empty."
      # ---------------------------------

      - name: Set up JDK 8 (Mandatory for 1.16.5)
        # Обязательно устанавливаем Java 8, которая нужна для Minecraft 1.16.5 и ForgeGradle 4
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        # Предоставляем права на выполнение файлу Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        # Запускаем стандартную команду сборки
        run: ./gradlew build --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LollikZombieShift
          # Путь к скомпилированному JAR-файлу
          path: build/libs/*.jar
