name: Build Mod
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with system Gradle
        run: gradle build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LollikZombieShift
          path: build/libs/*.jar
