name: Build Mod
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Mandatory for 1.16.5)
        # Установка Java 8 (JDK 1.8)
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      # --- КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: УСТАНОВКА И ИСПОЛЬЗОВАНИЕ КОНКРЕТНОГО GRADLE ---
      - name: Install and Run Gradle 6.8.3
        # Вместо использования 'gradlew' (который ломается), мы вручную загружаем
        # и используем версию Gradle, совместимую с Forge 1.16.5.
        run: |
          # 1. Загружаем и распаковываем Gradle 6.8.3
          GRADLE_VERSION=6.8.3
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip gradle-${GRADLE_VERSION}-bin.zip -d /tmp/
          
          # 2. Добавляем исполняемый файл в PATH для текущего шага
          echo "/tmp/gradle-${GRADLE_VERSION}/bin" >> $GITHUB_PATH
          
          # 3. Запускаем сборку, используя команду 'gradle'
          # 'gradle build' теперь будет использовать версию, которую мы только что установили.
          gradle build
      # ------------------------------------------------------------------------

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LollikZombieShift
          path: build/libs/*.jar
